### ISSUE TITLE
Discussion: commit messages and link of commits to issues

### ISSUE THREAD

**Issue by ThiloteE** [RealRaven2000/quickFilters#113]
Axel, two separate issues i want to mention here:

1. I have seen that sometimes you don't have commit messages for certain commits. When I check news from Filtaquilla and quickfilters ([here](https://github.com/RealRaven2000/quickFilters/commits/master)) I can't just scroll through, but instead have to enter every commit without message to know and find out if you MIGHT have fixed, changed or added certain things I (and potentially other users) care about. I personally am happy for every commit message. Just wanted to let you know.

2. None of the commits in the list link to issues; A recent example is https://github.com/RealRaven2000/quickFilters/issues/108#issuecomment-1148859920.

   I appreciate that you notify that the issue has been fixed. Though, I would argue, there are certain benefits of having linked commits:
   1. It notifies users and developers of changes in the application
   2. It allows users and developers to review code
   3. It makes it easier to find relevant code in the mid/long term when inspecting old issues.
   4. It deals with differing expectations by letting users know what exactly has changed.
   5. It makes it easier to find out if an issue is still relevant and can be closed or not.

   See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue for a how to. I am not sure if you were aware, or if you made a conscious desicion not to, so here I go.

**Comment by ThiloteE** [comment]
(This came up, because I wanted to check the status of quickfilters and filtaquilla with regard to betterbirds complex filters integration)

**Comment by RealRaven2000** [comment]
> Axel, two separate issues i want to mention here:
> 
> 1. I have seen that sometimes you don't have commit messages for certain commits. When I check news from Filtaquilla and quickfilters ([here](https://github.com/RealRaven2000/quickFilters/commits/master)) I can't just scroll through, but instead have to enter every commit without message to know and find out if you MIGHT have fixed, changed or added certain things I (and potentially other users) care about. I personally am happy for every commit message. Just wanted to let you know.
> 2. None of the commits in the list link to issues; A recent example is [Edit fields of custom search term "Reply-To" is not displayed in Thunderbird 102 #108 (comment)](https://github.com/RealRaven2000/quickFilters/issues/108#issuecomment-1148859920).


not sure if I can do this with my regular check-ins. i can add a comment but I am currently using TortoiseSVN as my front end- not sure how to link the commit to an issue (other than mentioning the issue # in the comment). Sometimes I wait with my commits until close to a release so it could be a commit that deals with many issues - I would usually use the tagged versions (on my hard drive these are just copies of my released XPI files) and compare one version to the previous release - but I do keep versions of every prerelease if I notice a regression within a single release cycle - only  these are not all committed to github as I build 10s or sometimes 100s of versions for a single release. I think if I commit more often I can somewhat alleviate the issue - but still not sure how to link commit <==> issue. Also I only close relevant issues on release date in order to avoid duplicates.

**Comment by ThiloteE** [comment]
Thank you for the response.

Mhm, maybe adding `fixes #theissueyouwanttoreference` to the commit message will create a link?

According to GitHubs documentation, this line will automatically create a link and closes the mentioned issue if the line is mentioned in the first message of a **pull-request**. I assume and hope this will work not only with pull-requests, but also when you push it directly to GitHub from a different front-end.

**Comment by RealRaven2000** [comment]
> Thank you for the response.
> 
> Mhm, maybe adding `fixes #theissueyouwanttoreference` to the comments will create a link?
> 

I started to use this new format in my commits - thanks for the suggestions.

**Comment by ThiloteE** [comment]
Thank you! :-)
