### ISSUE TITLE
104.0b3 - not compatible.

### ISSUE THREAD

**Issue by aprojanos71** [RealRaven2000/quickFilters#124]

**Comment by RealRaven2000** [comment]
You probably found that quickFilters is restricted to only working with the ESR version (102.*) - this is done via the manifest entry:

```json
      "strict_max_version" : "102.*"
```

and is a precaution as I cannot constantly test my Add-ons against beta versions. If you want to have a try you use the build below - if you find any particular stuff that doesn't work with it please append it in a comment. Note that beta versions of Thunderbird may have bugs in them that can propagate into Add-ons, in which case it sometimes makes no sense to write a fix in the Add-on.

[quickFilters-wx-5.6pre25.zip](https://github.com/RealRaven2000/quickFilters/files/9304140/quickFilters-wx-5.6pre25.zip)

To install, download the zip file and drag it into Thunderbird Add-ons Manager. Do not extract the files.

**Comment by aprojanos71** [comment]
Work, but "quickFiltes Assitant" button does not work, and not activ.

**Comment by RealRaven2000** [comment]
I installed 104.0b3 and the assistant button goes red at least:

![image](https://user-images.githubusercontent.com/6314674/184479109-4b7b259e-5533-4745-873c-74a8eef0dc40.png)

No errors in the console at this stage. Also, the assistant is triggered when I drag mail. Can you check your main Error console

(Ctrl_Shift+J).

You can also check the Add-on specific error console for the web-extension parts using tools / developer tools / debug add-ons and then the "Inspect" button on quickFilters:

![image](https://user-images.githubusercontent.com/6314674/184479170-80339b04-2add-472c-bd82-57bcabb55086.png)

Again, I am not seeing any errors here

**Comment by aprojanos71** [comment]
![ScreenShot165](https://user-images.githubusercontent.com/78041865/184479650-4a6f094c-2a84-4ed0-96c6-5571b5248aa8.jpg)

**Comment by RealRaven2000** [comment]
Can you add more context?  Is this happening immediately after startup or when you click something? I cannot read your Thunderbird 's mind ...

More context:
1) enable these 3 Errors / Warnings / Logs
2) you can copy the complete log with right-click (as text)

![image](https://user-images.githubusercontent.com/6314674/184480052-18ac1cce-8676-409c-841d-1e5b4b46c624.png)

Also, can you expand the TypError: quickFiters.Util.licenseInfo error so that we may see the stack trace?
![image](https://user-images.githubusercontent.com/6314674/184480124-26bac91a-72f5-452c-8e21-71fd62bd3b7d.png)

**Comment by aprojanos71** [comment]
![ScreenShot166](https://user-images.githubusercontent.com/78041865/184480366-0c0ff708-8a52-4887-b985-9b57efad6ecc.jpg)

**Comment by aprojanos71** [comment]
![ScreenShot166](https://user-images.githubusercontent.com/78041865/184480389-edff3156-e3ea-4649-8f1c-76849d14400c.jpg)

**Comment by aprojanos71** [comment]
mail.activity: OnDownloadError: Beérkezett üzenetek of katona1010@gmail.com
2 autosync.jsm:395:16
NS_ERROR_NOT_AVAILABLE: PreferDisplayName: undefined - not a boolean 8 AddrBookCard.jsm:365
mail.activity: OnDownloadError: Beérkezett üzenetek of katona1010@gmail.com
autosync.jsm:395:16
TypeError: quickFilters.Util.licenseInfo is undefined quickFilters.js:800:14
    onToolbarButtonCommand chrome://quickfilters/content/quickFilters.js:800
    onLoad jar:file:///D:/AJ_DATA/AJ_MOZILLA/AJ_MOZILLA/aj71.default-beta/extensions/quickFilters@axelg.com.xpi!/chrome/content/scripts/qFi-messenger.js:66
mail.activity: OnDownloadError: Beérkezett üzenetek of katona1010@gmail.com
2 autosync.jsm:395:16

**Comment by RealRaven2000** [comment]
Some Initialisation is missing on your system.

Can you enable debug mode and then switch on notifications:
![image](https://user-images.githubusercontent.com/6314674/184492791-ca321dce-8012-409b-a394-fa5c946f67c2.png)

`extensions.quickfilters.debug.notifications = true`

![image](https://user-images.githubusercontent.com/6314674/184492831-e8b803b4-a7ea-4d2d-a97d-82b587a7c4d2.png)

PS: If you cannot open the quickFilters settings dialog (because of the error) you can edit the settings in tools / settings / general / {config editor...]

```
extensions.quickfilters.debug = true
extensions.quickfilters.debug.notifications = true

```

Don't forget to **enable the first 3 options** in the error console (errors / warnings / info) or we will miss context!!

![image](https://user-images.githubusercontent.com/6314674/184492761-e83becf6-dc4b-41a0-a88b-5358a30bc3cc.png)

Then _restart Thunderbird_ and capture the complete log from startup.

Latest version as baseline:

[quickFilters-wx-5.6pre28.zip](https://github.com/RealRaven2000/quickFilters/files/9331334/quickFilters-wx-5.6pre28.zip)

expected output should look something like this (I tested both with a valid quickFilters license and en empty license):

```
quickFilters {NOTIFICATIONS} [logTime init]
[object Object]
quickFilters 12:53:10.186  [0 ms]   
Version() getter. addonInfo:
quickFilters 12:53:10.187  [1 ms]   
Adding Custom Term: Reply-To
quickFilters {NOTIFICATIONS} 12:53:10.197  [10 ms]   
onBackgroundUpdates - dispatching custom event quickFilters.BackgroundUpdate.toggleCurrentFolderButtons
into chrome://messenger/content/messenger.xhtml
quickFilters 12:53:10.197  [0 ms]   
toggleCurrentFolderButtons()
quickFilters {NOTIFICATIONS} 12:53:10.198  [1 ms]   
onBackgroundUpdates - dispatching custom event quickFilters.BackgroundUpdate.updatequickFiltersLabel
into chrome://messenger/content/messenger.xhtml
quickFilters 12:53:11.202  [1004 ms]   
=================quickFilters==============
   checkFirstRun() - attempt 1
quickFilters 12:53:11.202  [0 ms]   
Version() getter. addonInfo:
quickFilters 12:53:11.202  [0 ms]   
firstRun = false  - currentVersion = 5.6pre28  - installed = 5.6
quickFilters 12:53:11.202  [0 ms]   
store installedVersion: 5.6

```

**Comment by aprojanos71** [comment]
![ScreenShot168](https://user-images.githubusercontent.com/78041865/184493744-83a0e03e-ad6f-4af0-98f1-501b716b4794.jpg)

**Comment by aprojanos71** [comment]
![ScreenShot169](https://user-images.githubusercontent.com/78041865/184493752-49aabd9e-5c4b-4187-ae6b-7efaf97bcf07.jpg)

**Comment by aprojanos71** [comment]
![ScreenShot170](https://user-images.githubusercontent.com/78041865/184493754-188d1a76-f72c-482a-9d33-489a45d8b611.jpg)

**Comment by RealRaven2000** [comment]
the btnApply is null  can be fixed. I still don't know why the licensInfo is not initialized by the notification listener you should see some messages starting with `quickFilters {NOTIFICATIONS}` - are you sure that logging "info" is enabled?

[quickFilters-wx-5.6pre29.zip](https://github.com/RealRaven2000/quickFilters/files/9331471/quickFilters-wx-5.6pre29.zip)

Made a fix for the btnApply message -  (I had made some changes in the meantime because of #122 - which affect you because you don't have all buttons on the toolbar:
![image](https://user-images.githubusercontent.com/6314674/184495111-302fbc57-a8b0-43b4-8ed4-2f48b35fdefc.png)

**Comment by aprojanos71** [comment]
installed 29.zip and the quickFilter toolbar has disappeared.

**Comment by aprojanos71** [comment]
![ScreenShot171](https://user-images.githubusercontent.com/78041865/184496481-7479f548-df62-4ae9-a955-94fd374cdcfd.jpg)

**Comment by aprojanos71** [comment]
15:33:52.308 unexpected token: identifier qFi-messenger.js:72:16
    _loadIntoWindow jar:file:///D:/AJ_DATA/AJ_MOZILLA/AJ_MOZILLA/aj71.default-beta/extensions/quickFilters@axelg.com.xpi!/chrome/content/api/WindowListener/implementation.js:968
    onLoadWindow jar:file:///D:/AJ_DATA/AJ_MOZILLA/AJ_MOZILLA/aj71.default-beta/extensions/quickFilters@axelg.com.xpi!/chrome/content/api/WindowListener/implementation.js:687
    checkAndRunExtensionCode resource:///modules/ExtensionSupport.jsm:218
    _checkAndRunMatchingExtensions resource:///modules/ExtensionSupport.jsm:190
    registerWindowListener resource:///modules/ExtensionSupport.jsm:69
    forEach self-hosted:3866
    registerWindowListener resource:///modules/ExtensionSupport.jsm:68
    startListening jar:file:///D:/AJ_DATA/AJ_MOZILLA/AJ_MOZILLA/aj71.default-beta/extensions/quickFilters@axelg.com.xpi!/chrome/content/api/WindowListener/implementation.js:569
    startListening self-hosted:1151
    result resource://gre/modules/ExtensionParent.jsm:1125
    withCallContextData resource://gre/modules/ExtensionParent.jsm:608
    result resource://gre/modules/ExtensionParent.jsm:1124
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:618
    result resource://gre/modules/ExtensionParent.jsm:1123
    callAndLog resource://gre/modules/ExtensionParent.jsm:1076
    recvAPICall resource://gre/modules/ExtensionParent.jsm:1122
    AsyncFunctionNext self-hosted:668

**Comment by RealRaven2000** [comment]
Sorry my fault- I had to rush out, and my office roof was being redone. typo! I typed `ig` insted of `if`. Fixed version:

[quickFilters-wx-5.6pre30.zip](https://github.com/RealRaven2000/quickFilters/files/9331908/quickFilters-wx-5.6pre30.zip)

once it is installed check what happens if you drag all 4 buttons into the toolbar. (You may have to restart the Add-on or Thunderbird afterwards, I don't think the click event handlers are added just by dragging to the toolbar - they are added when quickFilters starts)

**Comment by aprojanos71** [comment]
Works fine! Thx! :-)

**Comment by RealRaven2000** [comment]
Any news on this?
