### ISSUE TITLE
Email downloading

### ISSUE THREAD

**Issue by mispam23** [RealRaven2000/quickFilters#128]
Hi,
your addon is fantastic. I'm using it to categorize emails with a label and a color.
There is just one thing I'd like to ask. 
To be honest I don't think it may be an issue, but maybe a wrong configuration in my TB:
I have my thunderbird with imap sync with a gmail account working without issues.
I created 4 filters to categorize my emails. I.E.: when an order from a client enters, it turns that email green in my inbox.

![filtro](https://user-images.githubusercontent.com/83295015/191233397-dd08593b-7476-42c6-8ea5-ffa33de63441.png)

Then I realised that every morning when I open thunderbird, it starts redownloading ALL emails (even when I can see them already in the thunderbird inbox!). Please see image attached:

![quickfilters question](https://user-images.githubusercontent.com/83295015/191230555-e851f52b-f3ea-40f4-a86a-85ed3b20456c.png)

I didn't know why this was happening and lagging my daily work, however It turns out that when I deactivate my 4 filters, this doesn't happen. If I activate them and reopen my thunderbird, it will start again downloading the whole inbox.

Is there something I need to change in my filter configuration so this doesn't happen?
Thank you in advance.

**Comment by RealRaven2000** [comment]
I had the same problem for a long while (but I mainly use POP3, as I always thought IMAP as unreliable and slow) - something is causing Cache invalidation on the folder, I am not sure what exactly. Can  you start with running the troubleshooter for the filters?

![image](https://user-images.githubusercontent.com/6314674/191243831-f381e6f2-852a-4f28-9db6-2774ca73e165.png)

PS: you can skip steps or disabling them by right-clicking the troubleshoot button.

**Comment by RealRaven2000** [comment]
You could also check the filter log for any filters that may have failed during startup ....

**Comment by mispam23** [comment]
Thank you for your quick answer. I tried both things.
The troubleshooting option didn't gave any error:
![troublesh-1](https://user-images.githubusercontent.com/83295015/191446302-c41d97f5-dbf7-4d24-9925-d1674e65e65f.png)

Also I can't find any error in the log. At least I don't think it is an error. All messages I can find at the log is like this one:
![log](https://user-images.githubusercontent.com/83295015/191446955-9d243f05-d6d2-4031-b87d-40548f4c00f8.png)

Is there anything else I could try for this? There must be something I'm doing wrong. So many people using your addon without issues, and for sure many of them with imap on gmail.

Checking in options I found something:
![options](https://user-images.githubusercontent.com/83295015/191447652-143ac790-1860-49b3-ba20-46d86941b8f5.png)

Would make any difference unticking this option?
Thank you in advance!

**Comment by RealRaven2000** [comment]
The filter log (by Thunderbird) will only tell you which filter is ran by Thunderbird, it's not really a troubleshooting tool.  I think that IMAP is poorly designed for folders with large amounts of emails (I very much prefer POP3 because it never gives me such troubles). Can you disable your filters and download all IMAP mail just to see whether this cures the problem? I am a little doubtful that it will really fix the situation, but if it does it actually has nothing to do with quickFIlters (when filters are run, quickFilters is not involved at all) - so even disabling / uninstalling quickFilters will make no difference. because it doesn't do anything unless you create a new filter (that's when it does it work).

I have disabled automatic downloading on my main IMAP account and only access is seldomly because it will try re-download about 25k messages every time I access it and totally slow down Thunderbird. To me that's just a waste of time. I was told that one should only have a few 100 messages there to minimize traffic, which isn't really a practical solution for thing like my support folders that retain mails from decades of work. That's why  I still believe POP is superior.

I am trying to find related bugs on bugzilla for you:

https://bugzilla.mozilla.org/show_bug.cgi?id=1597927
https://bugzilla.mozilla.org/show_bug.cgi?id=1461194
https://bugzilla.mozilla.org/show_bug.cgi?id=707446

Maybe it is time to create a new bug on bugzilla to get to the bottom of this Thunderbird problem - if you do then make sure to link it here so I can add my own comments.

**Comment by mispam23** [comment]
You are totally right. The problem is not related to your filter. 
I uninstalled TB and created a simple filter with TB, and if it is active, it will redownload all my inbox. It might be a conjunction with TB and imap probably as you say.

I'll investigate further and post here if I find some workaround.

Thank you for your support!

**Comment by RealRaven2000** [comment]
Maybe also check Error console (Ctrl+Shift+J) for errors, I would enable "info" and "Debug" so you can get errors from Thunderbird itself:

![image](https://user-images.githubusercontent.com/6314674/191460602-58740aa0-fe4b-4d56-be07-447b6d9ad2bf.png)
