### ISSUE TITLE
Thunderbird crashes with quickFilters 5.7.1

### ISSUE THREAD

**Issue by wsmwk** [RealRaven2000/quickFilters#152]
@RealRaven2000 

All crashes have quickFilters 5.7.1 installed. The earliest dating to Dec 26. 
Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1808092

**Comment by RealRaven2000** [comment]
@wsmwk - Can we find out whether _they had quickFilters assistant activated_ during the time of crash? Some people set the assistant to automatically start with Thunderbird (so they may not be aware that it is running):

![image](https://user-images.githubusercontent.com/6314674/213676412-83458103-05bf-4351-800d-73cadb59ee3a.png)

The typical use case would be to activate it manually, then moved some emails manually and it will help with generating / auto-filling filters.

The major change in this version is that (following advice from @jobisoft)  it removes monkey-patched code that was replacing the global `MsgMoveMessage` and `MsgCopyMessage` functions - it instead tries to use a folder listener to activate the assistant. At this stage we do not know what causes the mail to be moved, so in order to rule out filter activity itself (we are only interested in user interaction moving the mail) we check all filters that may have moved mail to the folder and if we find one and it matches the mail in all search terms, we do not open the assistant. 

See  `quickFilters.MsgFolderListener.msgsMoveCopyCompleted()`

[link to code](https://github.com/RealRaven2000/quickFilters/blob/ESR91/chrome/content/quickFilters.js#L1381)

This may take some time, but it follows the message being moved, I am not aware whether it would hold up filter execution to the point of crashing(?) - I don't really know how to read the crash report you linked.

I could avoid checking for matching filters if there was some global flag / status I could look at that could tell me that filtering is currently active. I couldn't really come up

**Comment by RealRaven2000** [comment]
PS: I would guess that they have filters that look into the body (content) of an email that are active at the time these filter are executed. I think searching message body contents can incur a great speed penalty. My assumption is that when the `msgsMoveCopyCompleted` event is triggered, the email has already been completely moved. Maybe there is a problem here with syncing / Imap?

**Comment by wsmwk** [comment]
On 1/20/23 5:43 AM, RealRaven2000 wrote:
>
> @wsmwk <https://github.com/wsmwk> - Can we find out whether /they had 
> quickFilters assistant activated/ during the time of crash? Some 
> people set the assistant to automatically start with Thunderbird (so 
> they may not be aware that it is running):
>
Unfortunately there is no way to contact anyone.

**Comment by RealRaven2000** [comment]
> > - Can we find out whether /they had quickFilters assistant activated/ during the time of crash? Some people set the assistant to automatically start with Thunderbird (so they may not be aware that it is running):
> Unfortunately there is no way to contact anyone.

ok then I will probably have to deal with it when users report more detail to me directly.

**Comment by RealRaven2000** [comment]
New version, reinstated the monkey patch functions and removed the code in the folder listener:

[quickFilters-wx-5.7.2pre65.zip](https://github.com/RealRaven2000/quickFilters/files/10528445/quickFilters-wx-5.7.2pre65.zip)

To install, download zip file above and drag into Thunderbird Add-ons Manager (without extracting contents).

**Comment by RealRaven2000** [comment]
Did a bunch of corrections and testing over at issue #145 - here is the latest version:

[quickFilters-wx-5.8pre87.zip](https://github.com/RealRaven2000/quickFilters/files/10570166/quickFilters-wx-5.8pre87.zip)

To install, download zip file above and drag into Thunderbird Add-ons Manager (without extracting contents).

**Comment by RealRaven2000** [comment]
Removed more service wrappers (using MailServices). Latest version:

[quickFilters-wx-5.8pre89.zip](https://github.com/RealRaven2000/quickFilters/files/10578569/quickFilters-wx-5.8pre89.zip)

To install, download zip file above and drag into Thunderbird Add-ons Manager (without extracting contents).

**Comment by RealRaven2000** [comment]
More refactoring of service wrappers after last Add-on Developers meeting yesterday night:

[quickFilters-wx-5.8pre104.zip](https://github.com/RealRaven2000/quickFilters/files/10710293/quickFilters-wx-5.8pre104.zip)

To install, download zip file above and drag into Thunderbird Add-ons Manager (without extracting contents).

**Comment by RealRaven2000** [comment]
Should be fixed with 5.8 released today.

**Comment by wsmwk** [comment]
> Should be fixed with 5.8 released today.

I agree. The crash is gone according to https://crash-stats.mozilla.org/signature/?signature=nsMsgBodyHandler%3A%3AnsMsgBodyHandler
