### ISSUE TITLE
Simplify toggling quickFilters Assistant on/off

### ISSUE THREAD

**Issue by jensmuehle** [RealRaven2000/quickFilters#192]
Thank you very much for you quick reply and the interesting workaround for getting an on/off button back.
Is it possible to completely hide the QuickFolders bar?
I tried various options in the settings, but so far couldn't find anything to hid the bar. That would be really great.

>There is a problem with this: in the new version of Thunderbird (115, which will go live next Monday), we are allowed one >button only to be added to the new unified toolbar, because they consolidated all toolbars, so I decided to combine all >commands into a single dropdown. They also do not support having 2 separate actions for the pushbutton and the >dropdown, its either a pushbutton or a dropdown, not both. 
>
>As an immediate workaround for the moment you can use the [QuickFolders ] toggle filter assistant button which is in the >center screen.
>
>>Until a while ago, I could just click on a button in Thunderbird to "Start Filter Assistant"/Stop.
>>
>>Then a change came where this became a two step, which I think is rather annoying.
>>
>>It would be great to have an option to make this a one step again. Or e.g., when you click on the button it Starts/Stops
> the >filter assistant, but then you click on the downward caret it brings up the menu?
>

**Comment by RealRaven2000** [comment]
> Thank you very much for you quick reply and the interesting workaround for getting an on/off button back.
> Is it possible to completely hide the QuickFolders bar?

Today I have made a prototype "toggle visibility" button for Thunderbird 115 - see https://github.com/RealRaven2000/QuickFolders/issues/351#issuecomment-1624083622

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/3b2ac113-e142-4e51-bc18-8f344b1fa144)

it is a little clunky at them moment because the API does not support "toggle" buttons for Add-ons natively, but @jobisoft said that it is planned to be added for one of the next releases.
