### ISSUE TITLE
quickFilters assistant not triggered by adding Tags to Emails

### ISSUE THREAD

**Issue by splinetime** [RealRaven2000/quickFilters#221]
Quick Filters does not recognize a tag action, it does not trigger the quickfilter dialog, whether activated in settings or not.
Thunderbird 115.3.2
Quick Filter 6.22

**Comment by RealRaven2000** [comment]
this is caused by the removal  of the global function ToggleMessageTag - this is now stored in multiple instances across different 3pane windows. Patch incoming later!

**Comment by RealRaven2000** [comment]
here is a patched version, have been working on this for the last 2 hours, so its still fresh. Note; it may not work (yet) on newly opened tabs, because it only patches the tag listener on all existing tabs when the ADd-on is loaded.

[quickFilters-wx-6.3pre31.zip](https://github.com/RealRaven2000/quickFilters/files/12893750/quickFilters-wx-6.3pre31.zip)

----

To test this version, download the zip file, drag the file into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by RealRaven2000** [comment]
@splinetime did you get a chance to test this version? If it works I will put the fix into the next version, will close the bug once it is released to the public.

**Comment by RealRaven2000** [comment]
Implemented in 6.3 - Published 18/10/2023
