### ISSUE TITLE
Cannot Create filter from Saved Search

### ISSUE THREAD

**Issue by froginperil** [RealRaven2000/quickFilters#227]
Hi Alex:

Thunderbird 115.5.0 (64-bit) (Linux)

Not a major problem. I have a number of different email addresses for different purposes including some advocacy. To simplify things, I have created a common inbox with a saved search on all messages from all inboxes. From a message there, if I right click -> create filter, nothing happens. I have to go to the individual inbox.

**Comment by RealRaven2000** [comment]
The problem with creating filters from various sources is in the actual design by Thunderbird: all filters are assigned (and stored) per account, so the assumption is that they are also ran per account. And there is no "global filter" that one could use maybe by specifying a condition based on "from" or "to". If that's something you want, have a look at Postbox instead, they have a "global" filter option (they use the same architecture but have a hack that copies and syncs the same filter across all accounts).

Filters are always triggered from the various Inboxes. And there is one single filter file (msgFilterRules.dat) in every mail box. So the whole design is not friendly to "pick and choose" type of filters. The filter trigger comes from the back end (programmed in C++) so there is no obvious hooks for even experemintal Add-ons like quickFilters to interfere. The only way would be reinventing the filtering mechanism in JavaScript (e,.g. based on a folder listener) and this would likely slow down the system significantly; so an Add-on is likely the wrong level to solve this problem.

So I have to close this one as `wontfix` unless Thunderbird changes the architecture and allows global filters or a multiple-selection in the account dropdown of the "edit filter" dialog. the only way to get this would be by raising a bug on Bugzilla. We would also need a dedicated C++ engineer in Thunderbird who knows everything about filters, because there is massive scope for improvements here (e.g. syncify actions / conditions).
