### ISSUE TITLE
Avoid Empty Conditions list due to removed recipients - filter cannot be edited

### ISSUE THREAD

**Issue by SKelem** [RealRaven2000/quickFilters#23]
For some reason, the past few times I used quickFilters to create a filter, the condition was unintentionally set to Recipient.
This creates a filter with no conditions and no way to create a condition.
![Screenshot from 2020-09-24 12-40-58](https://user-images.githubusercontent.com/599385/94196249-f0e7d300-fe68-11ea-8d6c-bfb0a7b3762f.png)
1. There should be a way to add conditions here.
After this window is dismissed, a message (that doesn't appear in a screen capture!) appears saying "quickFilters Email addresses were omitted from the conditions - quickFilt..."
2. The message comes only after dismissing the useless popup. If it came before the popup, and before it moves the messages to the destination folder, then the action could be remedied.  The only way to fix this is to turn off quickFilters, move the message back from the dest folder to the src folder, turn on quickFilters, remember to change the condition, and then things will be fine.
Actually, it would be best if the message were issued before the first quickFilters popup is dismissed, or prevented the popup from being dismissed.

I hope this helps make quickFilters better!
Steve

**Comment by RealRaven2000** [comment]
I will log this as enhancement. Hopefully I will be able to address it once we have quickFilters compatible with Thundebird 78.

**Comment by RealRaven2000** [comment]
As a quick workaround: should we return to the assistant where the filter template is selected if the conditions list will be empty? One could show a message: with the current filter template "by recipients", no meaningful filter conditions can be created, please select a different template.

**Comment by RealRaven2000** [comment]
Here is my solution. Instead of creating a nonsensical filter that cannot be edited and wasting the users time, I display this message:
[quickFilters-wx-4.5pre7.zip](https://github.com/RealRaven2000/quickFilters/files/6211777/quickFilters-wx-4.5pre7.zip)

![image](https://user-images.githubusercontent.com/6314674/112631046-50319a80-8e2e-11eb-9486-85bcfb433e9b.png)

Trial version (Tb78):
[quickFilters-wx-5.2pre30.zip](https://github.com/RealRaven2000/quickFilters/files/6211774/quickFilters-wx-5.2pre30.zip)
Trial version (Tb68):

**Comment by RealRaven2000** [comment]
Implemented in releases 4.5 + 5.2
