### ISSUE TITLE
Quick filters or quick folders?

### ISSUE THREAD

**Issue by dgcruzing** [RealRaven2000/quickFilters#38]
Isn't this a little confusing to run with two different extensions in the same hub?

Why not keep them separate until you join them as at the moment we are following Quickfilters here until we get the official stable release to use for Thunderbird or am I missing something here?

Noted, I did load it and will play, but as I have 3 machines that are tied back to Thunderbird and quick filters, it's bad enough trying to keep them synced.. 

so this brings up another question that has been on my mind. 
Can I export all Quickfilters database to say cloud storage and then load it back into another machine?

I actually work off 3 machines in any one day with emails open so this would be a perfect way to keep them all working with the same filters.. At the moment I use one machine to open emails in the morning to sort and the others just have to make do until the next day. 

But back to the original question.. Two different Extensions.. with the view to merging into one?

**Comment by RealRaven2000** [comment]
> Isn't this a little confusing to run with two different extensions in the same hub?
> 
> Why not keep them separate until you join them as at the moment we are following Quickfilters here until we get the official stable release to use for Thunderbird or am I missing something here?

At first I didn'tr understand what you were saying until I read an email this morning - I accidentally uploaded QuickFolders to the quickFilters github. There is no intention of merging both Add-ons as they do fundamentally different things and both already have complicated, highly configurable user interfaces. It would be both to hard to grasp from the user's point and much more difficult to maintain for us developers. But the good news is that the quickFilters release is now ready for publishing I will shortly upload that.

As regards keeping multiple machines in sync, this is very difficult to automate especially because there are no GUIDs (or any other external data) that can be stored in the filtering structure, so the only way we can merge into existing filters is by looking a the filter name, which not the most reliable way. You can still export / import manually with the right-most toolbar buttons on the filters list:

![image](https://user-images.githubusercontent.com/6314674/100539748-748abb00-3230-11eb-808d-2c6ab3ff3c0b.png)

**Comment by RealRaven2000** [comment]
Fixed with (the real and final) release 5.0 for Thunderbird 78:

https://github.com/RealRaven2000/quickFilters/releases/tag/5.00
