### ISSUE TITLE
missing condition "Folder name"

### ISSUE THREAD

**Issue by ltdeta** [RealRaven2000/quickFilters#4]
Why does the condition "Folder name" not exist in the filter rules. In FiltaQuilla there is this possibility as well.

So it is not possible (except in the "Filter" dialog) to apply rules only to a specific folder.
All rules are always executed. There is no possibility to set rules only for a specific folder.

**Comment by RealRaven2000** [comment]
> 
> 
> Why does the condition "Folder name" not exist in the filter rules. In FiltaQuilla there is this possibility as well.

Can you come up with a concrete example of what you want exactly? My guess is you want the filter assistant add the current mail folder as condition automatically, is that it?

To make quickFilters assistant more powerful, you can use both Add-ons together. To make a filter template use the "custom template" feature:

![image](https://user-images.githubusercontent.com/6314674/76144221-f53bd280-6075-11ea-8fef-ff687a6518cc.png)

this will create a new template that can do more stuff for you automatically. In FiltaQuilla you add the condition "Folder Name" (I trust you have already tested that functionality and it works if you generate a filter manually?)

![image](https://user-images.githubusercontent.com/6314674/76144252-6d09fd00-6076-11ea-86e5-b79724f64a0b.png)

You can then make a template that has the condition "folder Name". The missing part I believe is the automatic filling of the current folder name; quickFilters is already able to extract header information from the assistant-analysed Email  (the email used to "teach" the assistant) in the drop-down "Custom Variables":

![image](https://user-images.githubusercontent.com/6314674/76144332-ffaa9c00-6076-11ea-97c5-b670f825e4d0.png)

However there is no entry here for "current folder location > name". If this were here then you could simply generate a new mail filter based on an email that was in folder "x" (e.g. Inbox / Bills / whatever) and it would automatically fill the match fields correctly. Is this what you are looking for?

Please make sure to test out the Custom templates feature to understand what it does (or ask questions here). This doesn't create filters but new entries in the filter assistant, which is ultimately what you are looking for: a quick way to generate filters based on existing emails / actions.

Big caveat: all filters are stored in the inbox and can only be automatically be executed from there. If you have a filter that operates on an email outside of the inbox you can only run this **manually**!!!!! This is by design (Thunderbird) and cannot be changed by an Add-on.

**Comment by ltdeta** [comment]
hanks for the quick answer
i will use both addons together

**Comment by RealRaven2000** [comment]
Ok, I will mark this one as fixed for now.
