### ISSUE TITLE
Feature request: multiple rule choice when auto-creating a filter

### ISSUE THREAD

**Issue by jakubstaszak-com** [RealRaven2000/quickFilters#46]
I've been using quickFilters for a short while now, and it has a potential to be really helpful. I definetly am missing one important feature: allowing multiple rules to be selected for auto-creating a new filter.

I often create filters based on some part of the subject AND sender's e-mail address. Possibility to only choose one, when creating a new filter, is definetly limiting.

Allowing multiple choices on that list would make this add-on much more functional in my opinion.

**Comment by RealRaven2000** [comment]
you can do this (if you have a quickFilters license) in "advanced" options:

- Open quickFilters settings (easiest via right-click on the filter assistant button)
- Click on the Advanced tab, enable Custom Templates and click on Create New...
![image](https://user-images.githubusercontent.com/6314674/107145635-e5d6a080-693a-11eb-9922-e12262c16da6.png)
- Enter the name of your template (this is what is going to be shown to you as a choice when creating new filters)
- This will open the filter editor but in "Custom Template" mode:

![image](https://user-images.githubusercontent.com/6314674/107145641-f8e97080-693a-11eb-8fe0-906c9c797ff2.png)

You can add conditions to "autofill" with the Custom Variables dropdown. I am using a similar placeholder syntax to what I do in my Add-on [SmartTemplates](https://addons.thunderbird.net/thunderbird/addon/smarttemplate4/). As an example it shows you how it can use the "From" field based on the mail address of the "from" mail header.

Note: As the target folder / other filter actions are being autofilled during filter creation, do not select this as the action. Since the filter must have at least one action I used "Set priority to Normal" as a placeholder, which hopefully should be fine.


In your case, you could then add "subject" and end with these 2 auto-filling conditions:

The resulting filter is going to be treated as a template (or additional choice) during the quickFilter assistant process to give you exactly the workflow you may need.

Also note that this filter template is stored in local folders, doesn't need to be activated and has to have the prefix "quickFilterCustomerTemplate: " in the name (this part is not shown in the template selection box but it important so that quickFilters finds it).

Next time you use the assistant you should see the new choice:

![image](https://user-images.githubusercontent.com/6314674/107145685-377f2b00-693b-11eb-9fce-a3729da07f24.png)
