### ISSUE TITLE
Problem with resendig emails with attachment

### ISSUE THREAD

**Issue by suko007** [RealRaven2000/quickFilters#80]
Hi from 19.11. I have a problem with filters which are resending mails with attachment to other emails. please help

quickfiters -  5.3.2.
TB - 91.3.2.

problem massage : 

Failed to send message.
An error occurred while trying to mount the file " xxx.pdf " . Make sure you have access to the file.

thanks a lot

**Comment by RealRaven2000** [comment]
Can you post a screenshot of the filter definition please? not quite sure where the forwarding message action comes from, is it a FiltaQuilla or a Thunderbird standard action?

**Comment by suko007** [comment]
https://prnt.sc/208vkug

**Comment by RealRaven2000** [comment]
I took the liberty of anonymizing your screenshot and inserting it directly. You can just paste images directly in the edit textfield here in github with any modern browser. Since I don't know the language I do not know what you have as the search condition. May there be a problem with diacritics not being matched from the body or subject?

If it is a Thunderbird issue, then there is not much I can do - quickFilters does not actually get involved in the filtering process at all, it only helps generating / managing filters. It doesn't do anything when the filters run.

**Comment by ITP2021** [comment]
Hello, we are experiencing the same issue. Filter-based forwarding of emails with attachement does not work because of access right issues. When using teh debugger the follwoing bug is reported:
Uncaught (in promise) Error: Missing host permission for the tab
Forwarding emails with attachement manually without using quick filters does work without any problem.
We think that this is not a TB problem, it is a quick filters problem.
Please, fix this bug. Thanks in advance

**Comment by RealRaven2000** [comment]
> Hello, we are experiencing the same issue. Filter-based forwarding of emails with attachment does not work because of access right issues. When using the debugger the following bug is reported: Uncaught (in promise) Error: Missing host permission for the tab Forwarding emails with attachment manually without using quick filters does work without any problem. We think that this is not a TB problem, it is a quick filters problem. Please, fix this bug. Thanks in advance

I am testing here - but even if I disable quickFilters and restart Thunderbird I still get the error message. If I look at the filter log I actually get a message that states the mail was forwarded:

```
[27/11/2021, 16:31:03] Applied filter "quickFilters - issue 80" to message from Axel Grude <axel.grude@gmail.com> - [quickFilters] issue 80: forward mail with attachment. 4 at 27/11/2021, 16:29:59 forwarded 
```

Further, I tried disabling my other Add-ons (QuickFolders, which also establishes folder listeners which I suspected were the cause of the problem and FiltaQuilla) - same result, always an error caused by mailnews.send:


```
16:34:09.106 Connection reset. irc.jsm:907
16:34:14.731 mailnews.send: Failed to fetch attachment; name=log.txt, url=file:///C:/Users/Axel/AppData/Local/Temp/nsmail-10.txt, error=asyncFetch failed with status=2152857618 MimePart.jsm:159:29
16:34:14.732 mailnews.send: 
Exception { name: "", message: "Failed to fetch attachment", result: 2153066778, filename: "resource:///modules/MimePart.jsm", lineNumber: 162, columnNumber: 0, data: XPCWrappedNative_NoHelper, stack: "getEncodedBodyString@resource:///modules/MimePart.jsm:162:26\n", location: XPCWrappedNative_NoHelper }
MessageSend.jsm:122:27
16:34:14.734 mailnews.send: Sending failed; There was an error attaching log.txt. Please check that you have access to the file., exitCode=2153066778, originalMsgURI=imap-message://thunderbirddaily%40gmail.com@imap.gmail.com/INBOX#2776?fetchCompleteMessage=true MessageSend.jsm:321:27
16:34:16.359 Connection reset. 2 irc.jsm:907

```

I then also disabled SmartTemplates and Copy Sent to Current, Category Manager and Message Header Toolbar Customize. Restarted. still same error message, even with a completely fresh Email (with attachment) - the error happens both when running the filter automatically (incoming) and manually. Could this be a Thunderbird bug?

**Comment by RealRaven2000** [comment]
PS: I wonder if the same error happens on a POP3 account?

**Comment by RealRaven2000** [comment]
I have asked about this in the Tb developers chat on matrix / element. Hopefully we will get an answer next week!

**Comment by RealRaven2000** [comment]
Possibly related recent changes in Tb codebase:

https://bugzilla.mozilla.org/show_bug.cgi?id=1735601

**Comment by RealRaven2000** [comment]
I think I found a related and _relevant_ bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1741805

**Comment by RealRaven2000** [comment]
> Hello, we are experiencing the same issue. Filter-based forwarding of emails with attachment does not work because of access right issues. When using teh debugger the follwoing bug is reported: Uncaught (in promise) Error: Missing host permission for the tab Forwarding emails with attachment manually without using quick filters does work without any problem. We think that this is not a TB problem, it is a quick filters problem. Please, fix this bug. Thanks in advance

To compare apples with apples, can you disable quickFilters and run the filter automatically? Also do you have the assistant switched off when Thunderbird starts? I just want to make sure it's not an active assistant that is causing this. A

**Comment by RealRaven2000** [comment]
Just a note - quickFilters does not run the filters or interact in any way while Thunderbird executes filters (regardless whether they were created with quickFilters or manually)
