### ISSUE TITLE
Permissions descriptions conflict on Mozilla add-ons

### ISSUE THREAD

**Issue by EagerOptions** [RealRaven2000/quickFilters#91]
add-on: quickFilters
Issue: conflicting permissions descriptions
URL: https://addons.thunderbird.net/en-US/thunderbird/addon/quickfilters/
When: 3 February 2022 for version 5.3.2
Issue:
From inside Thunderbird 78.14.0 (Mac), viewing the add-on's page at the above URL, the quickFilters page "Permissions" link (just right of the green "+ Add to Thunderbird" button) lists the add-on's required permission as:

This add-on can:

Display notifications to you

However, once the user clicks the "+ Add to Thunderbird" button, the permissions warning popup lists the same add-on's permissions as:

Have full, unrestricted access to Thunderbird, and your computer

And once the add-on is installed, its Permissions tab also lists its permissions as:

Have full, unrestricted access to Thunderbird, and your computer

I'm confused, and I'm sure other users are also. Can you fix, please? (I'm very much looking forward to exploring all the cool things quickFilters can do.)

**Comment by RealRaven2000** [comment]
Even when you ue the latest version of Thunderbird (91.5) and you will see that quickFilters needs full permissions - this is because was ported from a legacy add-on using experimental APIs. As long as it is  in this class of extensions there cannot be any single permissions like with the newer API-based Add-ons. First all the code hast to be rewritten. Of course you then also won't have a modified search options box or a toolbar within the message filter list - API Add-on are not allowed to modify the User Interface in this way. It's going to take a while to completely rewrite the Add-on to use only built in APIs (an possibly take a lot of functionality away).

**Comment by EagerOptions** [comment]
Wow, what a lot of work for you!

And thanks for the quick and clear explanation.

Why does the permissions link on the app page just list the permissions as "Display notifications to you"? Is that an auto-generated thing? (You're obviously a meticulous developer, and I'm finding the same issue with other people's add-ons.)

**Comment by RealRaven2000** [comment]
I think I know what's happening.  these pages are inherited and controlled
by Firefox, which doesn't allow experimental Add-ons. When we use
experiments to include our own experimental APIs (and in order to retain
our "hacked" Tb-specific back end code) we require the full permissions.

However we can also include official to APIs such as folders, message,
account- these have to be registered in our manifest in the permissions
section just like with a web extension in Firefox.

if it wouldn't have to ask for full permission on install (on account of
being experimental) it would still have to ask for permissions on these
points. I guess this is part of the process when converting until the
Add-on is fully compatible and finally submitted to the permissions system
as planned by the web extension mechanism.

so I guess even though it looks like a contradiction, both statements
(needs full permissions & needs special permissions for API access) are
correct at the same time. I am not sure whether Thunderbird can actually
change the way the Add-ons pages are presented.

**Comment by EagerOptions** [comment]
I think you must be correct -- see the reply to my bug report about the overall problem [here](https://github.com/thundernest/addons-server/issues/178). It's sure confusing for us users, unfortunately. I'm new to Thunderbird, and most of the best add-ons I've found (such as yours) seem to be in the same situation.
